include: package:very_good_analysis/analysis_options.5.1.0.yaml

analyzer:
  errors:
    prefer_typing_uninitialized_variables: ignore
    public_member_api_docs: ignore
    use_build_context_synchronously: ignore

linter:
  rules:
