name: ordrio_shoppi
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  auto_route: ^9.2.2
  cloud_firestore: ^5.4.5
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  firebase_auth: ^5.3.2
  firebase_core: ^3.7.0
  firebase_storage: ^12.3.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  get_it: ^8.0.2
  image_picker: ^1.1.2
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.19.0

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
